apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-world
  namespace: hello-world
spec:
  source:
    type: Git
    git:
      uri: https://github.com/koz4/hello-world-gitops.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: hello-world:latest
  triggers:
    - type: ConfigChange
